name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: npm intall
        run: |
          npm install -y
      -
        name: npm build
        if: success()
        run: |
          unset CI
          npm run build
      -
        name: npm eject
        if: success()
        run: |
          npm run eject -y
      -
        name: ls
        if: success()
        run: |
          ls
